# Generated by Django 5.0.1 on 2024-01-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paid', models.CharField(choices=[('карта', 'карта'), ('платежный счет', 'платежный счет')], max_length=14)),
                ('type_card_account', models.FloatField(max_length=16)),
                ('fio', models.FloatField(max_length=64, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('limit', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField(max_length=16)),
                ('status', models.CharField(choices=[('Ожидает оплаты', 'Ожидает оплаты'), ('Оплачена', 'Оплачена'), ('Отменена', 'Отменена')], max_length=14)),
                ('requisite', models.ManyToManyField(to='shop.requisites')),
            ],
        ),
    ]
