# Generated by Django 5.0.1 on 2024-01-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='fio',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='limit',
            field=models.CharField(blank=True, default='0', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='type_card_account',
            field=models.CharField(max_length=16),
        ),
    ]
